preview:
  samples: 10
  max_depth: 10
  scale: 4
  num_threads_width: 10
  num_threads_height: 10

render:
  samples: 200
  max_depth: 20
  scale: 1
  num_threads_width: 10
  num_threads_height: 10

camera:
  vfov: 40
  aperture: 0.0
  focus_distance: 10000
  pos:
    pos: [ 278, 278, -800 ]
  look_at:
    pos: [ 278, 278, 0 ]

screen:
  width: 600
  height: 600

loader:
  Sandbox

image_output_dir: "../"

image_action:
  WaitForSignal

tone_map:
  Aces:
    default: true
