preview:
  samples: 2
  max_depth: 4
  scale: 4
  num_threads_width: 10
  num_threads_height: 10

render:
  samples: 100
  max_depth: 20
  scale: 1
  num_threads_width: 10
  num_threads_height: 10

screen:
  width: 640
  height: 480

loader:
  Yml:
    path: ../resources/scenes/three_balls.yml

image_output_dir: "../"

image_action:
  WaitForSignal # (SavePng, WaitForSignal)
